#!/command/with-contenv bash
# shellcheck shell=bash

# copy default app
if [[ ! -d "/app" || -z "$(ls -A /app)" ]]; then
    mkdir /app
    cp -nr /defaults/app/* /app/
fi

# permissions
cont-chown -R abc:abc /app